#!/usr/bin/env python
"""Generate THIRD_PARTY_LICENSES.md from installed package metadata (importlib.metadata).

Run with the project venv so the metadata is the one actually installed:
    .venv/Scripts/python.exe scripts/gen_third_party_licenses.py

Direct dependencies = requirements.txt. Transitive = the installed closure of their Requires-Dist
(markers/extras evaluated only for the `uvicorn[standard]` extra; other extras are skipped).
Packages that are required only on other platforms (uvloop on Windows...) are listed as "not installed
here" instead of being guessed.
"""
from __future__ import annotations

import importlib.metadata as md
import re
import sys
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def norm(n: str) -> str:
    return re.sub(r"[-_.]+", "-", n).lower()


def read_requirements(path: Path) -> list[str]:
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        if not line or line.startswith("-"):
            continue
        out.append(re.split(r"[\[=<>!~ ;]", line)[0])
    return out


def license_of(d: md.Distribution) -> str:
    m = d.metadata
    expr = m.get("License-Expression")
    if expr:
        return expr
    cls = [c.split("::")[-1].strip() for c in (m.get_all("Classifier") or []) if c.startswith("License ::")]
    lic = (m.get("License") or "").strip()
    if lic and len(lic) <= 60 and "\n" not in lic:
        return lic if not cls else f"{lic} ({'; '.join(cls)})"
    if cls:
        return "; ".join(cls)
    return "UNKNOWN (see package)" if not lic else "see package (long license text)"


def home_of(d: md.Distribution) -> str:
    m = d.metadata
    if m.get("Home-page"):
        return m["Home-page"]
    for u in m.get_all("Project-URL") or []:
        label, _, url = u.partition(",")
        if label.strip().lower() in {"homepage", "home", "source", "repository", "documentation"}:
            return url.strip()
    urls = m.get_all("Project-URL") or []
    return urls[0].partition(",")[2].strip() if urls else "-"


def closure(roots: list[str]):
    seen: dict[str, md.Distribution | None] = {}
    q = deque(roots)
    while q:
        n = q.popleft()
        k = norm(n)
        if k in seen:
            continue
        try:
            d = md.distribution(n)
        except md.PackageNotFoundError:
            seen[k] = None
            continue
        seen[k] = d
        for r in d.requires or []:
            if "extra ==" in r and not ("uvicorn" in k and "standard" in r):
                continue
            q.append(re.split(r"[ ;<>=!~\[(]", r)[0])
    return seen


def table(rows):
    L = ["| Package | Version | License | Home page |", "|---|---|---|---|"]
    for name, ver, lic, home in sorted(rows, key=lambda r: r[0].lower()):
        L.append(f"| {name} | {ver} | {lic.replace('|', '/')} | {home} |")
    return L


def main() -> int:
    direct = read_requirements(ROOT / "requirements.txt")
    seen = closure(direct)
    dkeys = {norm(n) for n in direct}
    rows_d, rows_t, missing = [], [], []
    for k, d in seen.items():
        if d is None:
            missing.append(k)
            continue
        row = (d.metadata["Name"], d.version, license_of(d), home_of(d))
        (rows_d if k in dkeys else rows_t).append(row)
    optional = read_requirements(ROOT / "requirements-optional.txt")

    L = [
        "# Third-party licenses",
        "",
        "Generated by `scripts/gen_third_party_licenses.py` from the metadata installed in the project venv "
        f"(Python {sys.version.split()[0]}). Anamnesia itself is MIT (see `LICENSE`). Re-run the script after "
        "changing `requirements.txt`. License strings are copied from each package's own metadata; they are "
        "not legal advice. Check the package for the authoritative text.",
        "",
        "## Runtime dependencies (`requirements.txt`)",
        "",
        *table(rows_d),
        "",
        f"## Transitive dependencies installed with them ({len(rows_t)})",
        "",
        *table(rows_t),
        "",
    ]
    if missing:
        L += ["Required by the above only on other platforms or as optional extras, so not installed here "
              "and therefore not listed with a license: " + ", ".join(sorted(missing)) + ".", ""]
    L += [
        "## Optional components (`requirements-optional.txt`): NOT installed by default, NOT redistributed",
        "",
        "None of these is a runtime dependency; every stage is off by default. This project does not bundle "
        "or redistribute their code or model weights. Each user downloads them directly and is bound by "
        "their licenses.",
        "",
        "- Optional pip packages named in the file: " + ", ".join(f"`{o}`" for o in optional) + ".",
        "- **Provence reranker/compressor** (`naver/provence-reranker-debertav3-v1`): **CC BY-NC-ND 4.0, "
        "personal / non-commercial use only**. Optional, off by default, never shipped in this repository "
        "or in the wheel. Do not enable it in a commercial deployment.",
        "- LLMLingua-2 code and `microsoft/llmlingua-2-xlm-roberta-large-meetingbank` model: MIT "
        "(as noted in `requirements-optional.txt`).",
        "- `BAAI/bge-reranker-v2-m3`, `mixedbread-ai/mxbai-rerank-base-v2`, `torch`, `transformers`, "
        "`sentence-transformers`: check each upstream license before use (not verified here).",
        "",
        "## External tools (not pip, not bundled)",
        "",
        "graphify, hermes, ollama: separate programs the user installs; their licenses apply to them.",
        "",
        "## Other bundled assets",
        "",
        "`data/synthetic_vault/` is generated by `scripts/gen_synthetic_corpus.py` (invented data, MIT with "
        "the project). `assets/logo.png`: project asset, owner to confirm authorship/license (unverified).",
        "",
    ]
    (ROOT / "THIRD_PARTY_LICENSES.md").write_text("\n".join(L), encoding="utf-8")
    print(f"direct={len(rows_d)} transitive={len(rows_t)} missing={len(missing)}")
    unknown = [r for r in rows_d + rows_t if r[2].startswith("UNKNOWN")]
    print("unknown license:", [r[0] for r in unknown])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
